### ISSUE TITLE
/rbd/pnpm-volume/2b8ad01c-af91-4e4c-abfb-00c65dbb274e/node_modules/.registry.npmjs.org/vscode-jsonrpc/8.0.0-next.7/node_modules/vscode-jsonrpc/lib/common/linkedMap.js:40         return this._head?.value;

### ISSUE THREAD

**Issue by Listlessness** [GizmoDevelopment/ramune#360]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [e.g. Chrome, Safari]
 - Version [e.g. 58]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone Xs]
 - OS: [e.g. iOS 14.7]
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by GizmoTjaz** [comment]
what

**Comment by Listlessness** [comment]
I doesn't work lol

**Comment by GizmoTjaz** [comment]
werks on my machine lel

**Comment by Listlessness** [comment]
What's your discord, so we can talk?

**Comment by GizmoTjaz** [comment]
Check my bio
